// Bundled original preset entries 5..10 from card.json byte-exact fallback
// Comments 5..10 map to anima,chibi,nikke,3,1,2 (mojibake repaired)
// Runtime matching lorebook entry wins, then bundled requested, then bundled 1.
export const BUNDLED_PRESETS: Record<string, string> = {
  "anima": "[Positive]\n(masterpiece, best quality:1.6), score_8, score_7, highres, detailed, cinematic lighting, thin line, (@starshadowmagician:1.2), (@nishikujic:0.6), (@kuzuvine:1.2), (@ezu \\(e104mjd\\):1.8),\n\n{{prompt}}\n\n[Negative]\n(worst quality, low quality:1.4), score_1, score_2, score_3, artist name, blurry, jpeg artifacts, lowres, censor, bad anatomy, (bad hands:1.3), extra digits, (@bb \\(baalbuddy\\):1.6), @nel-zel formula, @konoshige \\(ryuun\\), @haganef, @saigalisk, @iesupa, @firolian, @foxicube, @cinnabus, @yukimaru ai, @mutsutake, shiny hair, eyelashes, long chin, (long jawline:1.4)",
  "chibi": "[Positive]\n<lora:Chibi:0.80> <lora:geffstyle-v0.4_800_steps:0.70> <lora:Anima_in_real_epoch_10:0.5>\nscore_7, score_8, score_9, masterpiece, very aesthetic, (mixed media:1.5), sensitive, @Ani2rel, no lineart, @geffstyle, sensitive, (mixed media:1.5), limited palette, warm colors, The painting style is highly textured, with thick, brush-like strokes and a rough, gritty quality. oil painting \\(medium\\), painting \\(medium\\),\n\n{{prompt}}\n\n[Negative]\nworst quality, low quality, score_1, score_2, score_3, text, detailed nose",
  "nikke": "[Positive]\n(@freng:1.5),(@sushispin:1.5),(@re0n:1.5),@0nineo9,goddess of victory: nikke,score 9,score 8,masterpiece,absurdres,very aesthtic,novel illustration,best quality,newest,year 2024,year2025,\n\n{{prompt}}\n\n[Negative]\n(@onikobe rin:1.5),(@ojipon:1.5),(@bb \\(baalbuddy\\):1.5),(@nyantcha:1.5),@bkub,@naga u,@mizuki hitoshi,(@taroimo \\(00120014\\):1.5),recent,worst quality,low quality,normal quality,score_1,score_2,score_3,artist name,jpeg artifacts,censored,bar censor,shotstack,(cross-eyed:1.2),narrow waist,elf ear,animal ear,body paint,looking at viewer,artist collaboration,username,ambiguous,mutated hands,realistic,head out of frame,(narrow waist:2.0),aged down,slender,thin,skinny,muscular,petite,chibi,anime screencap,extra fingers,extra toes,long body,bad body,missing fingers,bad hands,mutated hands and fingers,malformed hands,too many fingers,fused fingers,bad feet,extra legs,extra arms,extra limb,poorly drawn face,small eyes,(poorly drawn hands:1.5),from below,",
  "3": "[Positive]\n@shionstyle, <lora:shionstyle_v3:1.0>, (aged up:2.0), (curvy), best quality, score_9, score_8, score_7, year 2025, newest, highres, absurdres, very aesthetic\n\n{{prompt}}\n\n[Negative]\naged down, loli, flat chest, small breasts, abstract background, dark, dark background, sagging breasts, worst quality, low quality, score_1, score_2, score_3, artist name, logo, water mark, bad hands, wrong hand, extra hands, fewer digits, extra digits, bad feet, bad anatomy, bad proportions, bad perspective, artistic error, bad leg, bad arm, bad neck, wrong foot, chibi",
  "1": "[Positive]\n@k144d, <lora:kieed_v9_step6000:1.0>, (aged up:2.0), (curvy), best quality, score_9, score_8, score_7, year 2025, newest, highres, absurdres, very aesthetic\n\n{{prompt}}\n\n[Negative]\naged down, loli, flat chest, small breasts, abstract background, dark, dark background, sagging breasts, worst quality, low quality, score_1, score_2, score_3, artist name, logo, water mark, bad hands, wrong hand, extra hands, fewer digits, extra digits, bad feet, bad anatomy, bad proportions, bad perspective, artistic error, bad leg, bad arm, bad neck, wrong foot, chibi",
  "2": "[Positive]\n<lora:riko77:1.0>, (aged up:2.0), (curvy), best quality, score_9, score_8, score_7, year 2025, newest, highres, absurdres, very aesthetic\n\n{{prompt}}\n\n[Negative]\naged down, loli, flat chest, small breasts, abstract background, dark, dark background, sagging breasts, worst quality, low quality, score_1, score_2, score_3, artist name, logo, water mark, bad hands, wrong hand, extra hands, fewer digits, extra digits, bad feet, bad anatomy, bad proportions, bad perspective, artistic error, bad leg, bad arm, bad neck, wrong foot, chibi"
};
export const BUNDLED_PRESET_FALLBACK_KEY = "1";
