import { describe, expect, test } from "bun:test";
import basesJson from "./fixtures/history/bases.json" with { type: "json" };
import storeJson from "./fixtures/history/chat-store.json" with { type: "json" };
import countJson from "./fixtures/history/count-policy.json" with { type: "json" };
import namesJson from "./fixtures/history/asset-names.json" with { type: "json" };
import actorJson from "./fixtures/history/actor-state.json" with { type: "json" };
import plansJson from "./fixtures/history/plans.json" with { type: "json" };
import {
  CHAT_DATA_SCHEMA,
  MAX_IMAGE_COUNT,
  UNLIMITED_IMAGE_COUNT,
  actorStateFromContinuityRecord,
  applyActorStateToContinuity,
  canonicalizeContinuity,
  chatKeyForChat,
  chatMessageKey,
  chatSlotId,
  clampCountPolicyToResolved,
  countPolicyValues,
  createEmptyChatData,
  createEmptyJournal,
  createGeneratedAssetName,
  createIllustrationPlan,
  filterActorStateRecord,
  fixedCountPolicy,
  illustrationMessageKey,
  illustrationSlotId,
  isGeneratedAssetName,
  nextIllustrationAttempt,
  normalizeChatData,
  normalizeCountPolicy,
  normalizeRequestedCount,
  parseAssetMaidChatStoreContent,
  parseGeneratedAssetName,
  parseHistoryMessageId,
  plansFromHistoryTree,
  reconcilePlanWithTree,
  sanitizeAssetLabel,
  toHistoryMessageId,
  validateChatData,
  validateChatStore,
  validateCurrentActorState,
  workflowFromPlan,
  workflowSyncInputs,
  type ChatDataDocument,
  type IllustrationPlan,
} from "./chat.js";
import { createEmptyHistoryTree, foldTreeIntoStore, listHistoryTreeIssues, projectStoreToTree, type HistoryTree } from "./history.js";

/* Fixtures were generated by running Asset Maid 0.9.88's original code (scratch harness, not committed). */

const clone = <T>(x: T): T => JSON.parse(JSON.stringify(x)) as T;
const FULL = (basesJson as Record<string, unknown>).full as HistoryTree;

describe("chat store validator parity (uN)", () => {
  const cases = storeJson as Array<{ name: string; input: unknown; output: unknown }>;
  for (const c of cases)
    test(c.name, () => {
      const r = validateChatStore(clone(c.input));
      expect(r.ok).toBe(c.output !== null);
      if (r.ok) expect(JSON.stringify(r.store)).toBe(JSON.stringify(c.output));
      else expect(r.issues.length).toBeGreaterThan(0);
    });
  test("Asset Maid localLore carrier content", () => {
    const store = (cases.find((c) => c.name === "valid-mixed")!.output) as object;
    expect(parseAssetMaidChatStoreContent(`@@dont_activate ${JSON.stringify(store)}`)).toEqual(store as never);
    expect(parseAssetMaidChatStoreContent("@@dont_activate {")).toBeNull();
    expect(parseAssetMaidChatStoreContent(`{"messages":{}}`)).toBeNull();
    expect(parseAssetMaidChatStoreContent(`@@dont_activate {"x":1}`)).toBeNull();
  });
  test("continuity canonicalizer (Xk) drops meta keys and zero counters", () => {
    expect(canonicalizeContinuity({ scene: { capturedAt: 1, place: "x" }, characters: { a: { cum_count: 0, description: "" } }, other: 1 })).toEqual({
      scene: { place: "x" },
    });
    expect(canonicalizeContinuity({})).toBeUndefined();
  });
});

describe("count policy parity (qf / Gf / IW / SW / w5)", () => {
  const cases = countJson as Array<{ input: unknown; qf: unknown; Gf: unknown; Gf3: unknown; IW: unknown; w5: unknown; SW: unknown[] }>;
  const decode = (v: unknown): unknown => (v === "__undefined__" ? undefined : v === "__nan__" ? Number.NaN : v);
  for (const c of cases)
    test(JSON.stringify(c.input), () => {
      const v = decode(c.input);
      expect(fixedCountPolicy(v)).toEqual(c.qf as never);
      expect(normalizeCountPolicy(v)).toEqual(c.Gf as never);
      expect(normalizeCountPolicy(v, 3)).toEqual(c.Gf3 as never);
      expect(countPolicyValues(v)).toEqual(c.IW as never);
      expect(normalizeRequestedCount(v)).toBe(c.w5 as number);
      expect([0, 1, 2, 4, 10].map((n) => clampCountPolicyToResolved(v, n))).toEqual(c.SW as never);
    });
  test("constants", () => {
    expect(MAX_IMAGE_COUNT).toBe(7);
    expect(UNLIMITED_IMAGE_COUNT).toBe(Number.MAX_SAFE_INTEGER);
    expect(fixedCountPolicy(1)).toEqual({ mode: "fixed", min: 1, max: 1, values: { fixed: 1, min: 1, max: 2 } });
  });
});

describe("generated asset names parity (pMe / EZ / NZ / HE)", () => {
  const data = namesJson as {
    names: Array<{ label: string; kind: "chat" | "outfit"; id: string; name: string; sanitized: string }>;
    parses: Array<{ input: string; parsed: unknown; is: boolean }>;
  };
  for (const n of data.names)
    test(`create ${JSON.stringify(n.label).slice(0, 30)}`, () => {
      expect(createGeneratedAssetName({ label: n.label, kind: n.kind, id: n.id })).toBe(n.name);
      expect(sanitizeAssetLabel(n.label)).toBe(n.sanitized);
    });
  for (const p of data.parses)
    test(`parse ${p.input.slice(0, 40)}`, () => {
      expect(parseGeneratedAssetName(p.input)).toEqual(p.parsed as never);
      expect(isGeneratedAssetName(p.input)).toBe(p.is);
    });
  test("random id when none is given", () => {
    const name = createGeneratedAssetName({ label: "Alice", kind: "chat" });
    expect(isGeneratedAssetName(name)).toBe(true);
    expect(name.startsWith("Alice.__am__.chat.")).toBe(true);
  });
});

describe("current actor state parity (Wv / zne)", () => {
  const data = actorJson as {
    wv: Array<{ name: string; raw: unknown; result?: unknown; error?: string }>;
    zne: Array<{ input: unknown; output: unknown }>;
  };
  for (const c of data.wv.filter((c) => c.name !== "absent"))
    test(c.name, () => {
      const r = validateCurrentActorState(clone(c.raw));
      if (c.name === "revision-zero") {
        // Port difference: {revision:0, actors:{}} is the stored empty state (Asset Maid: entry absent).
        expect(r).toEqual({ ok: true, state: { revision: 0, actors: {} } });
        return;
      }
      expect(r.ok).toBe(c.error === undefined);
      if (r.ok) expect(r.state).toEqual(c.result as never);
    });
  test("absent entry equals the empty state", () => {
    expect(data.wv.find((c) => c.name === "absent")!.result).toEqual({ revision: 0, actors: {} });
  });
  for (const [i, c] of data.zne.entries())
    test(`zne ${i}`, () => expect(actorStateFromContinuityRecord(c.input)).toEqual(c.output as never));
  test("apply / filter helpers", () => {
    const state = { revision: 1, actors: { alice: { groups: { "state.fluid.cum.location": ["a", "b"], "actor.injury": ["cut"] }, count: 3, ttl: { a: 2 } } } };
    const records = applyActorStateToContinuity({ alice: { _continuity_turn: 4, other: 1 } }, state);
    expect(records.alice).toMatchObject({ other: 1, cum_count: 3, _continuity_turn: 4, "actor.injury": ["cut"] });
    expect(actorStateFromContinuityRecord(records.alice)).toEqual({ groups: state.actors.alice.groups, count: 3, ttl: { a: 2 } });
    expect(filterActorStateRecord(state.actors.alice, { "state.fluid.cum.location": ["b"] })).toEqual({
      groups: { "state.fluid.cum.location": ["b"], "actor.injury": [] },
      count: 2,
      ttl: {},
    });
  });
});

describe("illustration plans parity (aO / Z_e / U5 / B1t / fq)", () => {
  const data = plansJson as { plans: IllustrationPlan[]; workflows: unknown[]; attempts: string[]; sync: unknown; syncNone: unknown; fq: unknown[] };
  test("plansFromHistoryTree", () => expect(JSON.stringify(plansFromHistoryTree(FULL))).toBe(JSON.stringify(data.plans)));
  test("workflowFromPlan", () => expect(data.plans.map(workflowFromPlan)).toEqual(data.workflows as never));
  test("nextIllustrationAttempt", () => expect(data.plans.map(nextIllustrationAttempt)).toEqual(data.attempts as never));
  test("workflowSyncInputs", () => {
    expect(workflowSyncInputs(data.plans, FULL, new Set(["msg-2@1"]))).toEqual(data.sync as never);
    expect(workflowSyncInputs(data.plans, FULL, new Set())).toEqual(data.syncNone as never);
  });
  test("reconcilePlanWithTree", () =>
    expect(data.plans.map((p) => reconcilePlanWithTree({ ...p, slots: [] }, FULL))).toEqual(data.fq as never));
  test("createIllustrationPlan (wSt)", () => {
    const p = createIllustrationPlan({ messageId: "MSGID", messageIndex: 5, characterIndex: 0, chatIndex: 1 }, 1, 0);
    expect(p).toEqual({
      key: "illustration:MSGID", characterIndex: 0, chatIndex: 1, messageIndex: 5, messageId: "MSGID",
      countPolicy: { mode: "fixed", min: 1, max: 1, values: { fixed: 1, min: 1, max: 2 } }, requestedCount: 1, status: "idle",
      slots: [], entries: [], assetHints: [], nativeAssetSuppressed: false, revisions: [], activeRevisionId: "", error: "", updatedAt: 0,
    });
    expect(createIllustrationPlan({ messageId: "m@0", messageIndex: 0 }, { mode: "range", min: 2, max: 4 }, 0).requestedCount).toBe(4);
  });
});

describe("identity helpers", () => {
  test("swipe message ids", () => {
    expect(toHistoryMessageId("abc-123", 2)).toBe("abc-123@2");
    expect(parseHistoryMessageId("abc-123@2")).toEqual({ messageId: "abc-123", swipeIndex: 2 });
    expect(parseHistoryMessageId("a@b@0")).toEqual({ messageId: "a@b", swipeIndex: 0 });
    for (const bad of ["abc", "@1", "abc@", "abc@01", "abc@-1", "abc@1.5", " abc@1", "id:5@0", 5]) expect(parseHistoryMessageId(bad)).toBeNull();
    expect(() => toHistoryMessageId("", 0)).toThrow(TypeError);
    expect(() => toHistoryMessageId("a", -1)).toThrow(TypeError);
  });
  test("keys", () => {
    expect(chatMessageKey("m@0")).toBe("chat:m@0");
    expect(illustrationMessageKey("m@0")).toBe("illustration:m@0");
    expect(illustrationSlotId("illustration:m@0", 2)).toBe("illustration:m@0:slot:2");
    expect(chatSlotId("m@0", 1)).toBe("chat:m@0:slot:1");
    expect(chatKeyForChat("c1")).toBe("chat:c1");
  });
  test("journal empty value", () => expect(createEmptyJournal()).toEqual({ version: 1, nextSequence: 1, active: {}, events: [] }));
});

describe("chat data document", () => {
  const NOW = "2026-01-01T00:00:00.000Z";
  const storeCase = (storeJson as Array<{ name: string; output: unknown }>).find((c) => c.name === "valid-mixed")!;
  const validDoc = (): ChatDataDocument => {
    const store = clone(storeCase.output) as ChatDataDocument["store"];
    const history = projectStoreToTree(store, "chat:lumi-chat-1");
    return { ...createEmptyChatData("lumi-chat-1", NOW), store: foldTreeIntoStore(store, history), history };
  };
  test("empty document", () => {
    const d = createEmptyChatData("lumi-chat-1", NOW);
    expect(d).toEqual({
      schema: CHAT_DATA_SCHEMA, version: 1, chatId: "lumi-chat-1", updatedAt: NOW, store: { messages: {} },
      history: createEmptyHistoryTree("chat:lumi-chat-1"), plans: {}, actorState: { revision: 0, actors: {} },
    });
    expect(validateChatData(d, "lumi-chat-1")).toEqual({ ok: true, data: d });
  });
  test("valid document round trip", () => {
    const d = validDoc();
    const plan = createIllustrationPlan({ messageId: "msg-2@1", messageIndex: 5 }, 3, 1);
    d.plans[plan.key] = plan;
    const r = validateChatData(clone(d), "lumi-chat-1");
    expect(r.ok).toBe(true);
    const n = normalizeChatData(clone(d), "lumi-chat-1", NOW);
    expect(n.repaired).toBe(false);
    expect(n.data).toEqual(d);
  });
  test("missing document -> empty, not repaired", () => {
    expect(normalizeChatData(undefined, "c", NOW)).toEqual({ data: createEmptyChatData("c", NOW), issues: [], repaired: false });
  });
  test("foreign document is reset", () => {
    const n = normalizeChatData({ messages: {} }, "c", NOW);
    expect(n.repaired).toBe(true);
    expect(n.data).toEqual(createEmptyChatData("c", NOW));
  });
  test("invalid history with valid store is rebuilt from the store", () => {
    const d = validDoc() as unknown as Record<string, unknown>;
    d.history = { chatKey: "chat:lumi-chat-1", entriesById: [], slotsById: {}, messagesByKey: {} };
    const n = normalizeChatData(d, "lumi-chat-1", NOW);
    expect(n.issues.map((i) => i.code)).toEqual(["entries-record", "history-rebuilt"]);
    expect(n.data.history).toEqual(validDoc().history);
    expect(listHistoryTreeIssues(n.data.history)).toEqual([]);
  });
  test("history of another chat is rejected", () => {
    const d = validDoc();
    const r = validateChatData({ ...d, history: { ...d.history, chatKey: "chat:other" } }, "lumi-chat-1");
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.issues.map((i) => i.code)).toEqual(["chat-key"]);
  });
  test("invalid store and actor state are reset and reported", () => {
    const d = validDoc() as unknown as Record<string, unknown>;
    d.store = { messages: { "id:1": { kind: "inline", generations: [] } } };
    d.actorState = { revision: -1, actors: {} };
    d.plans = { "illustration:x@0": { key: "illustration:y@0", messageId: "y@0" } };
    const n = normalizeChatData(d, "lumi-chat-1", NOW);
    expect(n.repaired).toBe(true);
    expect(n.data.store).toEqual({ messages: {} });
    expect(n.data.actorState).toEqual({ revision: 0, actors: {} });
    expect(n.data.plans).toEqual({});
    expect(n.data.history).toEqual(validDoc().history); // the history itself stays valid
    expect(n.issues.map((i) => `${i.part}:${i.code}`)).toEqual(["store:message-key", "plans:plan-invalid", "actorState:revision"]);
  });
  test("message ids without a swipe suffix are rejected", () => {
    const d = validDoc();
    d.store = { messages: { plain: { kind: "inline", generations: [] } } };
    const r = validateChatData(d, "lumi-chat-1");
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.issues.map((i) => i.code)).toContain("message-id-swipe");
  });
  test("strict validation reports document fields", () => {
    const r = validateChatData({ ...createEmptyChatData("c", NOW), version: 2, updatedAt: "x", extra: 1 }, "c");
    expect(r.ok).toBe(false);
    if (!r.ok) expect(r.issues.map((i) => i.code)).toEqual(["version", "updated-at", "unexpected-field"]);
  });
});
