import { describe, expect, test } from "bun:test";
import basesJson from "./fixtures/history/bases.json" with { type: "json" };
import validatorJson from "./fixtures/history/validator.json" with { type: "json" };
import commandsJson from "./fixtures/history/commands.json" with { type: "json" };
import commitJson from "./fixtures/history/commit.json" with { type: "json" };
import updatersJson from "./fixtures/history/updaters.json" with { type: "json" };
import projectJson from "./fixtures/history/project.json" with { type: "json" };
import foldJson from "./fixtures/history/fold.json" with { type: "json" };
import {
  HISTORY_ISSUE_CODES,
  HistoryCommandError,
  HistoryInvariantError,
  MAX_GENERATED_ENTRIES_PER_SLOT,
  appendGeneratedEntry,
  applyHistoryCommand,
  applyHistoryCommands,
  canonicalizeHistoryTree,
  commitRevision,
  createEmptyHistoryTree,
  deleteGeneratedEntry,
  foldTreeIntoStore,
  latestGeneratedEntry,
  listHistoryMessages,
  listHistoryTreeIssues,
  listRevisionSlots,
  mutateHistoryTree,
  parseHistoryTree,
  projectStoreToTree,
  resolveHistorySlot,
  serializeHistoryTree,
  syncIllustrationWorkflows,
  validateHistoryTree,
  type CommitRevisionInput,
  type HistoryCommand,
  type HistoryTree,
  type IllustrationWorkflowSyncInput,
} from "./history.js";
import type { ChatStore } from "./chat.js";

/* Fixtures were generated by running Asset Maid 0.9.88's original code (scratch harness, not committed). */

type Json = unknown;
type Ref = { value?: Json; base?: string; patch?: Array<[Array<string | number>, Json?]> };
const BASES = basesJson as Record<string, Json>;
const clone = <T>(x: T): T => JSON.parse(JSON.stringify(x)) as T;

function resolve(ref: Ref, ctx: { input?: Json; previous?: Json } = {}): any {
  if ("value" in ref) return clone(ref.value);
  const base = ref.base === "$input" ? ctx.input : ref.base === "$previous" ? ctx.previous : BASES[ref.base as string];
  let out: any = clone(base);
  for (const op of ref.patch ?? []) {
    const path = op[0];
    if (!path.length) {
      out = clone(op[1]);
      continue;
    }
    let parent: any = out;
    for (const k of path.slice(0, -1)) parent = parent[k];
    const last = path[path.length - 1] as string;
    if (op.length === 1) delete parent[last];
    else parent[last] = clone(op[1]);
  }
  return out;
}

function errorMatches(fn: () => unknown, expected: string): void {
  let caught: unknown;
  try {
    fn();
  } catch (e) {
    caught = e;
  }
  expect(caught).toBeInstanceOf(Error);
  const e = caught as HistoryCommandError;
  const texts = [e.message, e.originalMessage];
  if (caught instanceof HistoryInvariantError) {
    // Asset Maid's invariant message is `${path}: ${korean}` per line.
    texts.push(caught.issues.map((i) => `${i.path}: ${i.messageKo}`).join("\n"));
  }
  expect(texts).toContain(expected);
}

const FULL = BASES.full as HistoryTree;
const CHAT = BASES.chat as HistoryTree;

describe("validator parity (hBe)", () => {
  const cases = validatorJson as Array<{ name: string; tree: Ref; issues: Array<{ code: string; path: string; message: string }> }>;
  test("fixture count", () => expect(cases.length).toBeGreaterThan(70));
  for (const c of cases)
    test(c.name, () => {
      const tree = resolve(c.tree);
      const issues = listHistoryTreeIssues(tree);
      expect(issues.map((i) => ({ code: i.code as string, path: i.path, message: i.messageKo }))).toEqual(c.issues);
      const r = validateHistoryTree(tree);
      expect(r.ok).toBe(c.issues.length === 0);
    });
  test("issue codes covered by fixtures", () => {
    const seen = new Set(cases.flatMap((c) => c.issues.map((i) => i.code)));
    const missing = HISTORY_ISSUE_CODES.filter((c) => !seen.has(c));
    expect(HISTORY_ISSUE_CODES.length).toBe(69);
    expect(missing).toEqual([]);
  });
  test("issues carry English and Korean text", () => {
    const [i] = listHistoryTreeIssues({ chatKey: "chat:x", entriesById: {}, slotsById: {}, messagesByKey: {}, x: 1 });
    expect(i).toEqual({
      code: "unexpected-field",
      path: "$.x",
      message: "Field is not defined in the persisted History schema.",
      messageKo: "History 영속 스키마에 정의되지 않은 필드입니다.",
    });
  });
});

describe("canonical form", () => {
  test("parse sorts record keys, serialize is stable", () => {
    const shuffled = clone(FULL);
    shuffled.entriesById = Object.fromEntries(Object.entries(shuffled.entriesById).reverse());
    const parsed = parseHistoryTree(JSON.stringify(shuffled));
    expect(Object.keys(parsed.entriesById)).toEqual(Object.keys(parsed.entriesById).sort((a, b) => a.localeCompare(b)));
    expect(serializeHistoryTree(shuffled)).toBe(serializeHistoryTree(FULL));
    expect(canonicalizeHistoryTree(shuffled)).toEqual(FULL);
  });
  test("parse rejects invalid JSON and invalid trees", () => {
    expect(() => parseHistoryTree("{")).toThrow(TypeError);
    expect(() => parseHistoryTree({ ...FULL, chatKey: "" })).toThrow(HistoryInvariantError);
  });
  test("empty tree", () => {
    expect(createEmptyHistoryTree(" chat:a ")).toEqual({ chatKey: "chat:a", entriesById: {}, slotsById: {}, messagesByKey: {} });
    expect(() => createEmptyHistoryTree(" ")).toThrow(TypeError);
  });
});

describe("command parity (Zne + PR + CR)", () => {
  const cases = commandsJson as Array<{ name: string; tree: Ref; commands: HistoryCommand[]; error?: string; result?: Ref; resultIssues?: string[] }>;
  for (const c of cases)
    test(c.name, () => {
      const input = resolve(c.tree) as HistoryTree;
      const before = clone(input);
      if (c.error !== undefined) {
        errorMatches(() => applyHistoryCommands(input, c.commands), c.error);
        return;
      }
      const out = applyHistoryCommands(input, c.commands);
      expect(out).toEqual(resolve(c.result as Ref, { input: before }));
      expect(JSON.stringify(out)).toBe(JSON.stringify(resolve(c.result as Ref, { input: before })));
      expect(listHistoryTreeIssues(out).map((i): string => i.code)).toEqual(c.resultIssues as string[]);
      expect(input).toEqual(before); // pure
    });
  test("every command type is covered", () => {
    const types = new Set(cases.flatMap((c) => c.commands.map((x) => x.type)));
    expect([...types].sort() as string[]).toEqual(
      [
        "add-message", "append-entry", "append-revision", "append-slot", "delete-entry", "delete-message", "delete-slot",
        "prune-slot", "set-active-revision", "set-default-entry", "set-illustration-workflow", "set-message-identity", "set-revision-outcome",
      ].sort(),
    );
  });
  test("99 generated entries per slot cap keeps the newest", () => {
    const k2 = "illustration:msg-2@1";
    const slotId = `${k2}:slot:0`;
    let tree = FULL;
    for (let i = 0; i < 120; i += 1)
      tree = applyHistoryCommand(tree, {
        type: "append-entry",
        messageKey: k2,
        revisionId: "revision:b",
        slotId,
        entry: { entryId: `g${i}`, slotId, kind: "generated", assetName: `a${i}`, createdAt: 10000 + i, width: 1, height: 1 },
        selectAsDefault: true,
      });
    const generated = Object.values(tree.entriesById).filter((e) => e.slotId === slotId);
    expect(generated.length).toBe(MAX_GENERATED_ENTRIES_PER_SLOT);
    expect(generated.some((e) => e.entryId === "g0")).toBe(false);
    expect(tree.entriesById.g119).toBeDefined();
    expect(listHistoryTreeIssues(tree)).toEqual([]);
  });
  test("delete-entry removes empty revisions and re-parents children", () => {
    const k2 = "illustration:msg-2@1";
    const t = applyHistoryCommands(FULL, [
      { type: "delete-entry", entryId: "generated:Bob-revision:a-0" },
      { type: "delete-entry", entryId: "generated:Bob-revision:a-1" },
      { type: "delete-entry", entryId: "generated:Bob-revision:a-2" },
    ]);
    const m = t.messagesByKey[k2]!;
    expect(m.revisions.map((r) => [r.revisionId, r.parentRevisionId])).toEqual([["revision:b", ""]]);
    expect(listHistoryTreeIssues(t)).toEqual([]);
  });
  test("mutateHistoryTree validates the result", () => {
    expect(() =>
      mutateHistoryTree(FULL, [{ type: "set-revision-outcome", messageKey: "illustration:msg-2@1", revisionId: "revision:a", status: "complete" }]),
    ).toThrow(HistoryInvariantError);
  });
});

describe("commitRevision parity (IBe.commitRevision + SBe)", () => {
  const cases = commitJson as Array<{ name: string; tree: Ref; inputs: CommitRevisionInput[]; steps: Array<{ error?: string; result?: Ref; json?: string }> }>;
  for (const c of cases)
    test(c.name, () => {
      let tree = resolve(c.tree) as HistoryTree;
      c.inputs.forEach((input, i) => {
        const step = c.steps[i]!;
        if (step.error !== undefined) {
          errorMatches(() => commitRevision(tree, clone(input)), step.error);
          return;
        }
        const out = commitRevision(tree, clone(input));
        expect(JSON.stringify(out)).toBe(step.json as string);
        tree = out;
      });
    });
});

describe("controller updaters parity", () => {
  const cases = updatersJson as Array<{ name: string; tree: Ref; op: string; arg: any; error?: string; result?: Ref }>;
  for (const c of cases)
    test(c.name, () => {
      const tree = resolve(c.tree) as HistoryTree;
      const run = () =>
        c.op === "sync"
          ? syncIllustrationWorkflows(tree, c.arg as IllustrationWorkflowSyncInput[])
          : c.op === "append"
            ? appendGeneratedEntry(tree, c.arg)
            : deleteGeneratedEntry(tree, c.arg as string);
      if (c.error !== undefined) return errorMatches(run, c.error);
      expect(JSON.stringify(run())).toBe(JSON.stringify(resolve(c.result as Ref, { input: tree })));
    });
});

describe("projection parity (NR / lK)", () => {
  const p = projectJson as Array<{ name: string; store: ChatStore; chatKey: string; indexes: Record<string, number>; tree?: HistoryTree; error?: string }>;
  for (const c of p)
    test(`project ${c.name}`, () => {
      if (c.error !== undefined) return errorMatches(() => projectStoreToTree(clone(c.store), c.chatKey, c.indexes), c.error);
      expect(JSON.stringify(projectStoreToTree(clone(c.store), c.chatKey, new Map(Object.entries(c.indexes))))).toBe(JSON.stringify(c.tree));
    });
  const f = foldJson as Array<{ name: string; store: ChatStore; tree: Ref; result?: ChatStore; error?: string }>;
  for (const c of f)
    test(`fold ${c.name}`, () => {
      const tree = resolve(c.tree) as HistoryTree | null;
      const store = clone(c.store);
      if (c.error !== undefined) return errorMatches(() => foldTreeIntoStore(store, tree), c.error);
      expect(JSON.stringify(foldTreeIntoStore(store, tree))).toBe(JSON.stringify(c.result));
      expect(store).toEqual(c.store); // pure
    });
  test("round trip store -> tree -> store -> tree is stable", () => {
    const c = p[0]!;
    const tree = projectStoreToTree(c.store, c.chatKey, c.indexes);
    const store2 = foldTreeIntoStore(c.store, tree);
    expect(projectStoreToTree(store2, c.chatKey, c.indexes)).toEqual(tree);
  });
});

describe("read helpers", () => {
  test("resolveHistorySlot / listRevisionSlots / latestGeneratedEntry / listHistoryMessages", () => {
    const k2 = "illustration:msg-2@1";
    const r = resolveHistorySlot(FULL, { slotId: `${k2}:slot:0` })!;
    expect(r.revision.revisionId).toBe("revision:b");
    expect(r.defaultEntry.entryId).toBe("generated:Bob-revision:b-0");
    expect(resolveHistorySlot(FULL, { slotId: `${k2}:slot:1` })).toBeNull();
    expect(resolveHistorySlot(FULL, { slotId: `${k2}:slot:1`, revisionId: "revision:a" })?.slot.slotIndex).toBe(1);
    expect(listRevisionSlots(FULL, k2, "revision:a").map((s) => s.slot.slotIndex)).toEqual([0, 1, 2]);
    const chat = resolveHistorySlot(CHAT, { slotId: "chat:msg-1@0:slot:0" })!;
    expect(latestGeneratedEntry(chat).kind).toBe("generated");
    expect(listHistoryMessages(FULL).map((m) => m.messageKey)).toEqual(["chat:msg-1@0", k2]);
  });
});
